# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 비나통(VinaTong)베트남 할인쿠폰
email: btmt2019@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  베트남은 비나통으로 통한다! 베트남 호치민 푸미흥 업소들의 할인쿠폰을 제공,소상공인 업소 홍보지원등 교민들을위한 정보공유 커뮤니티
url: "https://vinatong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jprimenet
github_username:  vinatong
timezone: Asia/Ho_Chi_Minh
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
google_site_verification: "WGZEl3xQD3TwJZ5LEDKXFsea_mhB5EbTweNIL-NjLyw"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
